### ISSUE TITLE
Flapping in singlestat panels

### ISSUE THREAD

**Issue by zmc** [ceph/cephmetrics#12]
I've heard reports from two people that the singlestat panels on the at-a-glance dashboard were flapping. I finally saw it myself. These were taken six seconds apart on the internal cluster:

<img width="201" alt="screen shot 2017-06-20 at 4 55 35 pm" src="https://user-images.githubusercontent.com/58307/27359535-7adfd3be-55d9-11e7-9fbc-c9333e52f313.png">
<img width="201" alt="screen shot 2017-06-20 at 4 55 41 pm" src="https://user-images.githubusercontent.com/58307/27359536-7adff970-55d9-11e7-9c86-a2ead52f9d4b.png">

**Comment by dmick** [comment]
I seem to be able to provoke this by clicking manual refresh like a crazed monkey, so it's just "sometimes the sample doesn't get data or gets bad data", it seems

**Comment by zmc** [comment]
Unsure if this is related:
https://paste.fedoraproject.org/paste/Vrvf9UVxjfEqMw35twVGdw

**Comment by pcuzner** [comment]
I think some of this is the interval issue - carbon is configured for 1s but collectd sends every 10s - so it fills in the blanks with null values - which the status panel really loves..

Zack is reconfiguring carbon, so we'll see whether the interval is the culprit.

**Comment by dmick** [comment]
I tried adding dumpio logs briefly to see what the params were to the POSTs, but it was awfully verbose and didn't immediately show anything useful.

**Comment by dmick** [comment]
It doesn't seem to be happening 9 out of 10 seconds, though.  Does carbon not interpolate?

**Comment by dmick** [comment]
it's possible using keepLastValue() in the graphite query for those items would mitigate the "I got a null sample" problem.  Hacked around a bit on a dashboard copied from the default At A Glance.

**Comment by pcuzner** [comment]
I'm not seeing this anymore - two things have changed
- interval is 10s on the whisper files, aligning to our collectd interval
- we have 2 monitors now reporting into graphite

closing as resolved

**Comment by dmick** [comment]
Resolved?..

Um..

**Comment by zmc** [comment]
I don't know that this is resolved

**Comment by pcuzner** [comment]
OK - so you guys are saying that after the config changes your still seeing the 'flapping' behaviour? I closed it because I had the dashboard open for a couple of hours and didn't see any issue.

**Comment by zmc** [comment]
Yeah, just happened again. These are from two consecutive refreshes:
<img width="224" alt="screen shot 2017-06-23 at 12 34 35 pm" src="https://user-images.githubusercontent.com/58307/27495748-6b66fa14-5810-11e7-9376-cb7277484ab9.png">
<img width="204" alt="screen shot 2017-06-23 at 12 34 43 pm" src="https://user-images.githubusercontent.com/58307/27495747-6b5cb928-5810-11e7-9bfc-b5905bded532.png">

**Comment by pcuzner** [comment]
this is down to the old dashboards query still being used. Updates to the dashboard have used keepLatValue to account for slow to arrive metrics from mons. zmc has a fixed to the ansible deployment that refreshes existing dashboards, which should ensure only the current/new version is active.

**Comment by zmc** [comment]
If I don't see this in the next ~24h I'll close the issue
